### ISSUE TITLE
Road to 1.0.0

### ISSUE THREAD

**Issue by i-like-robots** [i-like-robots/chai-html#7]
- [x] Add code linting (#8)
- [x] Add code coverage (#9)
- [x] Add more realistic test cases (#11)
